spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parking-garage
    username: tec_garage
    password: tec_garage
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop